/*
 * KubePi Restful API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type InternalModelV1ClusterSpec struct {
	Authentication *InternalModelV1ClusterAuthentication `json:"authentication,omitempty"`
	Connect *InternalModelV1ClusterConnect `json:"connect,omitempty"`
	Local bool `json:"local,omitempty"`
}
