/*
 * KubePi Restful API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type KubepiRepoConfig struct {
	AllowAnonymous bool `json:"allowAnonymous,omitempty"`
	ApiVersion string `json:"apiVersion,omitempty"`
	Auth bool `json:"auth,omitempty"`
	BuiltIn bool `json:"builtIn,omitempty"`
	ContinueToken string `json:"continueToken,omitempty"`
	CreateAt string `json:"createAt,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	Credential *ImagerepoCredential `json:"credential,omitempty"`
	Description string `json:"description,omitempty"`
	DownloadUrl string `json:"downloadUrl,omitempty"`
	EndPoint string `json:"endPoint,omitempty"`
	Kind string `json:"kind,omitempty"`
	Limit int32 `json:"limit"`
	Name string `json:"name,omitempty"`
	Page int32 `json:"page"`
	RepoName string `json:"repoName,omitempty"`
	Search string `json:"search,omitempty"`
	Type_ string `json:"type,omitempty"`
	UpdateAt string `json:"updateAt,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	Version string `json:"version,omitempty"`
}
