/*
 * KubePi Restful API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type KubepiRepoResponse struct {
	ContinueToken string `json:"continueToken,omitempty"`
	Items []string `json:"items,omitempty"`
}
