/*
 * KubePi Restful API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type KubepiUser struct {
	ApiVersion string `json:"apiVersion,omitempty"`
	Authenticate *UserAuthenticate `json:"authenticate,omitempty"`
	BuiltIn bool `json:"builtIn,omitempty"`
	CreateAt string `json:"createAt,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	Description string `json:"description,omitempty"`
	Email string `json:"email,omitempty"`
	IsAdmin bool `json:"isAdmin,omitempty"`
	Kind string `json:"kind,omitempty"`
	Language string `json:"language,omitempty"`
	Mfa *UserMfa `json:"mfa,omitempty"`
	Name string `json:"name,omitempty"`
	NickName string `json:"nickName,omitempty"`
	Type_ string `json:"type,omitempty"`
	UpdateAt string `json:"updateAt,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}
