/*
 * KubePi Restful API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type KubepiUserCreateReq struct {
	Authenticate *KubepiUserAuthenticate `json:"authenticate,omitempty"`
	Email string                         `json:"email,omitempty"`
	IsAdmin bool                         `json:"isAdmin,omitempty"`
	Mfa *DocsMfa                         `json:"mfa,omitempty"`
	Name string                          `json:"name,omitempty"`
	NickName string                      `json:"nickName,omitempty"`
	Roles []string                       `json:"roles,omitempty"`
}
