/*
 * KubePi Restful API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type V1ClusterAuthentication struct {
	BearerToken string                `json:"bearerToken,omitempty"`
	Certificate *V1ClusterCertificate `json:"certificate,omitempty"`
	ConfigFileContent []int32         `json:"configFileContent,omitempty"`
	Mode string                       `json:"mode,omitempty"`
}
